'use strict';
const fs=require('fs');
const P='D:/AI/WorkBuddy/2026-08-27-23-46-21/nas-music-scraper/prototype/data/result.json';
const d=JSON.parse(fs.readFileSync(P,'utf8'));
console.log('top keys:',Object.keys(d));
console.log('meta keys:',Object.keys(d.meta));
console.log('entries:',d.entries.length);
console.log('telemetry:',JSON.stringify(d.telemetry,null,1));
const e=d.entries[0];
console.log('entry0 keys:',Object.keys(e));
console.log('entry0 local:',JSON.stringify(e.local));
console.log('entry0 restored:',e.restoredTitle,'|',e.restoredArtist);
console.log('entry0 queriesTried:',JSON.stringify(e.queriesTried));
console.log('entry0 ne valid:',e.netease.valid,'tier',e.netease.tier,'relaxed',e.netease.tierRelaxed);
console.log('entry0 ne attempts:',JSON.stringify(e.netease.attempts));
console.log('entry0 topCandidates[0]:',JSON.stringify(e.netease.topCandidates[0]));
console.log('entry0 bestScore:',JSON.stringify(e.netease.bestScore));
console.log('entry0 lyrics:',JSON.stringify(e.netease.lyrics).slice(0,300));
console.log('entry0 mb attempts:',JSON.stringify(e.musicbrainz.attempts));
console.log('summary keys:',Object.keys(d.meta.summary||{}));
console.log('summary:',JSON.stringify(d.meta.summary,null,1).slice(0,4000));
